server:
  port: 8080
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true #서버 재시작없이 바로 업데이트됨

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  #  redis:
  #    host: 192.168.30.42
  #    port: 6379
#Encoding UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true

  datasource:
    # java config 자동 설정 시
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/postgres/public
#    username: postgres
#    password: root

    # java config 수동 설정 시
    hikari:
      maximum-pool-size: 4
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      jdbc-url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/postgres
      jdbc-url: jdbc:log4jdbc:postgresql://172.30.1.57:5432/postgres
#      jdbc-url: jdbc:log4jdbc:postgresql://172.30.1.7:5432/postgres
#      jdbc-url: jdbc:log4jdbc:postgresql://192.168.30.20:5432/postgres

      username: postgres
      password: root
    sql-script-encoding: UTF-8 # SQL 인코딩 옵션

# logback.xml 대신 설정할 수 있음(https://supawer0728.github.io/2018/04/07/spring-boot-logging/)
#logging:
#  level:
#    root: warn
#    com.vm.elk.controller.MainController: info

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 필드 속성 네임을 언더 스코어 -> 카멜 케이스